####################################################
#                                                  #
#                      Lg TV                       #
#                                                  #
####################################################
  - platform: webostv
    host: 192.168.1.22
    name: Living Room TV  
    timeout: 5
    filename: webostv.conf
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: !secret webostv


####################################################
#                                                  #
#                      Kodi                        #
#                                                  #
####################################################

  - platform: kodi
    host: 192.168.1.3 